In [10]:
import mysql.connector
import pandas

In [11]:
conn = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'nashit'
)

In [12]:

query = 'SELECT * FROM world.country'
df = pandas.read_sql('SELECT * FROM world.countrylanguage', conn)
conn.close()

C:\Users\s_nas\AppData\Local\Temp\ipykernel_10300\4006956241.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pandas.read_sql('SELECT * FROM world.countrylanguage', conn)

In [13]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB       Tonga          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [14]:
import pandas
import mysql.connector

In [19]:
a = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'nashit'
)

In [20]:
b = 'SELECT * FROM world.city'
df = pandas.read_sql(b, a)
a.close()

C:\Users\s_nas\AppData\Local\Temp\ipykernel_10300\1098394750.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pandas.read_sql(b, a)

In [21]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [22]:
df1 = pandas.read_json('ITR-1_2023_Main_V1.0.json')
df1

,$schema,type,additionalProperties,properties,definitions
ITR,http://json-schema.org/draft-04/schema#,object,False,{'$ref': '#/definitions/ITR'},"{'type': 'object', 'description': 'This is roo..."
ITR1,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
CreationInfo,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'This elemen..."
Form_ITR1,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'This is the..."
PersonalInfo,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Enter perso..."
FilingStatus,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
clauseiv7provisio139iType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
ITR1_IncomeDeductions,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Income and ..."
ITR1_TaxComputation,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Tax computa..."
TaxPaid,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Tax paid de..."
Refund,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Refund deta..."
Schedule80G,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
Schedule80GGA,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
Schedule80D,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TDSonSalaries,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Salary TDS ..."
TDSonOthThanSals,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': '22. Details..."
ScheduleTDS3Dtls,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Details of ..."
ScheduleTCS,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TaxPayments,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Tax payment..."
Verification,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Verificatio..."
TaxReturnPreparer,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'TRP details..."
BankAccountDtls,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Bank detail..."
AssesseeName,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Assessee na..."
Address,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Address of ..."
IntrstPay,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TaxesPaid,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
DoneeWithPan,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TDSonSalary,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TDSonOthThanSal,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TDS3Details,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
TaxPayment,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Tax payment..."
AddressDetail,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
EmployerOrDeductorOrCollectDetl,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Dedcutor De..."
CountryCode,http://json-schema.org/draft-04/schema#,object,False,NaN,{'description': '93:AFGHANISTAN; 1001:ÅLAND IS...
BankDetailType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
UsrDeductUndChapVIAType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Deductions ..."
DeductUndChapVIAType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'description': 'Deductions ..."
AllwncExemptUs10DtlsType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
OtherSourceIncome,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
NOT89AType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
DateRangeType,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
ExemptIncAgriOthUs10Type,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'object', 'additionalProperties': Fal..."
nonEmptyString,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'string', 'pattern': '|(\s*([\w\d_=!@..."
nonZeroString,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'pattern': '.*[1-9].*', 'allOf': [{'$ref': '#..."
endWithDigit,http://json-schema.org/draft-04/schema#,object,False,NaN,"{'type': 'string', 'pattern': '.*[0-9]'}"

In [26]:
df2 = pandas.read_json("C:/Users/s_nas/Downloads/EmployeeData.json")
df2

,id,name,email,password,about,token,country,location,lng,lat,...,sendmenotifications,sendTextmessages,enabletagging,createdAt,updatedAt,livelng,livelat,liveLocation,creditBalance,myCash
0,4051,manoj,manoj@gmail.com,Test@123,None,7f471974-ae46-4ac0-a882-1980c300c4d6,NaN,None,0.0000,0.000000,...,False,False,False,2020-01-01T11:13:27.1107739,2020-01-02T09:16:49.284864,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",127,0
1,4050,pankaj,p1@gmail.com,Test@123,None,e269eeef-1de1-4438-885a-e30a9ad26106,NaN,None,0.0000,0.000000,...,False,False,False,2020-01-01T07:39:34.1618239,2020-01-01T07:39:34.161824,0.000000,0.000000,None,0,0
2,3050,Neeraj1993,neeraj.singh@adequateinfosoft.com,286956,None,562c2fb5-6799-4b51-8733-a60564c96adc,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-27T10:16:05.6578091,2019-12-27T10:22:30.8416992,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",0,0
3,3049,Sophia,sophia@gmail.com,Test@123,Yo,f3bc9393-ad13-41a2-a69b-b607a42d829f,NaN,"18302 Lorance Trail, Little Rock, AR 72206, USA",0.0000,0.000000,...,False,False,False,2019-12-26T07:36:22.3481221,2019-12-26T07:36:22.3481222,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",36,0
4,3048,Raju Prasad,raju.nsit@gmail.com,Raju@1234,Don't Quit Your Day Dream,b3eda104-0771-4804-8be2-0e6d7c16412d,NaN,"Karbala Rd, Block G, Sector 5, Dakshinpuri, Ne...",0.0000,0.000000,...,True,True,True,2019-12-26T07:17:08.3460039,2019-12-26T14:27:00.4327446,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",5,0
5,3047,Ankiish Thapliyal,thapliyalankiish958@gmail.com,Test@1234,I failed many opportunities may times but I am...,caf070df-d2c2-4e99-ba06-9482ef5eb7ba,NaN,Dehradun,0.0000,0.000000,...,True,True,True,2019-12-26T07:13:01.9262534,2019-12-30T11:11:00.4082038,77.379004,28.630186,"Suite No. 203 H - 15 Rise tower, Sector 63, H ...",167,0
6,3046,Aryan Thapliyal,ashithewarrior@gmail.com,Test@1234,Testing is required for an effective performan...,c8cb5636-cd01-4133-adac-360cecc710af,NaN,Dehradun,0.0000,0.000000,...,False,False,False,2019-12-26T07:10:53.2318238,2019-12-30T05:32:04.0700419,77.379012,28.630237,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",160,0
7,3045,shivam,shivam@gmail.com,Shivam@123,None,59b6f0af-fc25-4a6b-b865-5fb29023c6df,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T07:01:24.5014557,2019-12-26T07:02:16.9663295,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",11,0
8,3044,Navya Upadhyay,navya.adequate@gmail.com,navya2123,None,0362f1b5-80be-4dff-bd40-c236c79561eb,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T06:53:22.1076016,2019-12-26T06:53:22.1076017,0.000000,0.000000,None,5,0
9,3043,Ritu singh,ritusinghadequate@gmail.com,ritusingh1234,None,a268517f-960a-418a-9c89-48708372702d,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T06:53:10.2343196,2019-12-26T06:53:10.2343197,0.000000,0.000000,None,5,0
10,3042,faiz,faizadequate@gmail.com,Test@1234,I am who I am. Your approval is not needed.,33dd5829-0a01-4b3b-80d3-1a63a75b3436,NaN,New Delhi,0.0000,0.000000,...,False,False,False,2019-12-26T06:30:58.6524884,2019-12-30T06:57:19.58494,77.379012,28.630232,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",38,0
11,3041,Martin Wilson,ravencomputer667@gmail.com,martin@123,"Travelers,",18ceb759-241c-43d3-a9eb-5344ea2ef1d9,NaN,"Moorgate Station (Stop N), London EC2Y 5EJ, UK",0.0000,0.000000,...,True,False,False,2019-12-26T06:22:36.1180762,2019-12-26T06:29:14.6591852,0.000000,0.000000,None,18,0
12,3040,Shweta Singh,amelia.claire.hi@gmail.com,Test@1234,What others think of me is none of my business...,e32b4e12-18f3-4fd0-9a3d-2021d8381dff,NaN,"India - Pakistan Border Rd, Bakhasar, Rajastha...",0.0000,0.000000,...,False,False,False,2019-12-26T06:20:51.0353245,2019-12-30T06:24:31.9803752,77.379004,28.630206,"Suite No. 203 H - 15 Rise tower, Sector 63, H ...",77,0
13,3039,jagjit,jagjit.singh.adequate.36@gmail.com,Test@1234,Take a chance and live life to the fullest. Wh...,1e150816-7075-4d6d-b3d6-eb1c0e415e61,NaN,"Delhi - Meerut Expy, Nai Basti Dundahera, Ghaz...",0.0000,0.000000,...,False,False,False,2019-12-26T06:20:32.873132,2020-01-02T06:29:36.6383214,77.379012,28.630190,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",32,0
14,3038,Ashi 123,ashi123@gmail.com,Test@1234,None,61a43ad3-02b3-4431-8c1b-1d29933147e1,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T05:30:27.4225101,2019-12-26T05:30:27.4225102,0.000000,0.000000,None,0,0
15,3037,shivamvermaa4,shivam.vemaa4@gmail.com,Shivam@123,None,97534ce9-5386-4b92-9741-fc1860bbcd1a,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T11:58:30.3613651,2019-12-24T11:58:30.3613651,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",10,0
16,3036,Sophia,n2@gmail.com,Test@123,WE,1ebfb0ac-7d98-43fb-ba41-0e40091c6071,NaN,"Saint-Louis-Strasse 3, 4056 Basel, Switzerland",0.0000,0.000000,...,False,False,False,2019-12-24T11:36:36.1739424,2019-12-26T09:48:57.2586835,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",45,0
17,3035,n1,n1@gmail.com,Test@123,An ordinary Bharitya,c40422ef-27ac-4e40-adf5-87403143dc99,NaN,451 DERA THAKRAN HARIDWAR ROAD MAHANT BALBIR S...,0.0000,0.000000,...,False,False,False,2019-12-24T11:36:03.4815197,2020-01-02T07:20:34.2742376,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",187,0
18,3034,neha,neha@gmail.com,Test@123,None,6aaaa999-8e14-40ca-b043-087624c48fd1,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T10:35:00.1292083,2019-12-24T10:35:00.1292083,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",53,0
19,3033,sanjay,sanjay@gmail.com,Test@123,None,c9989beb-685a-41d7-b6de-77dd208979df,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T08:16:23.8466413,2019-12-24T08:16:23.8466414,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",81,0
20,3032,Akku2,akku2@gmail.com,zxcvbnm1,None,12ac2112-c7b3-47d3-8d48-e839a1ce3955,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T07:30:32.9445148,2019-12-24T07:30:32.9445148,77.379047,28.630220,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
21,3031,Ashish Thapliyal,ashi1@gmail.com,Test@1234,"I Am Who I Am, Your Approval Is Not Needed. I ...",8889db9b-01f6-4305-b07d-aecc516037bb,NaN,"NH34, Shatabdi Nagar, Rithani, Meerut, Uttar P...",0.0000,0.000000,...,True,True,True,2019-12-24T06:52:08.6757278,2020-01-02T06:30:51.6595305,77.379017,28.630194,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",206,0
22,3030,singh,singh@gmail.com,Test@123,jdfgjghjgf,280a1f00-8597-4eee-8d46-9c8d5a120ac7,NaN,"Jg Halli Rd, Karnataka 577533, India",0.0000,0.000000,...,False,False,False,2019-12-24T06:32:23.0727945,2019-12-24T09:39:40.1944746,77.389824,28.628582,"noidya sector 63 Vidya polymer, Chhijarsi, Sec...",30,0
23,3029,Akku Testing,akku1@gmail.com,zxcvbnm1,"For some reason you've got ""bootstrap-sass"": ""...",7b0400eb-cd4f-45df-a8db-0c0871d46906,NaN,"Noida-Greater Noida Expressway, Amit Nagar, Sa...",0.0000,0.000000,...,True,True,False,2019-12-24T06:31:54.9038705,2019-12-24T13:00:12.9520741,77.379025,28.630216,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",161,0
24,3028,Aakankshi Gupta,aakankshi.cuminte@gmail.com,116331365713184193775,None,c916c01f-5844-445b-9f5a-e60d77ecb620,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T06:56:43.320768,2019-12-16T06:56:43.3207681,77.379024,28.630210,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
25,3026,Manresh Chandra 5,manresh5@gmail.com,zxcvbnm1,about.me is a personal web hosting service co-...,3c8ad706-9667-477a-adb6-3539f7b10a67,NaN,Deák Ferenc tér,0.0000,0.000000,...,True,True,False,2019-12-16T05:13:28.5717641,2019-12-16T05:13:28.5717641,77.379034,28.630178,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
26,3025,Manresh Chandra 4,manresh4@gmail.com,zxcvbnm1,None,8131e59d-7c83-4024-9423-0639a5887b52,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:11:34.473505,2019-12-16T05:11:34.473505,0.000000,0.000000,None,0,0
27,3024,Manresh Chandra 3,manresh3@gmail.com,zxcvbnm1,None,dc752b59-3d36-4b07-bc5c-6cd5913bae83,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:03:39.4564421,2019-12-16T05:03:39.4564423,0.000000,0.000000,None,3,0
28,3023,Manresh Chandra 2,manresh2@gmail.com,zxcvbnm1,None,867f49f2-8af8-45bf-9bd5-28ec641d3c44,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:01:14.0246654,2019-12-16T05:01:14.0246654,0.000000,0.000000,None,0,0
29,3022,Raju Prasad,raju.prasad@adequateinfosoft.com,Raju@1234,None,58ecfd42-7f10-440e-8007-29c6fa524040,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T14:36:34.2151655,2019-12-13T14:36:34.2151655,0.000000,0.000000,None,0,0
30,3021,Ashok Patel,ashoktest@gmail.com,ashokpatel457,None,520302ff-b08d-445f-be70-11c02d257e7e,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T13:47:59.4288322,2019-12-13T13:47:59.4288322,0.000000,0.000000,None,3,0
31,2021,manresh1,manresh1@gmail.com,zxcvbnm1,None,9305e1c5-82e2-4a79-b0ca-37bb5880f505,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T13:17:31.2904215,2019-12-13T13:17:31.2904216,0.000000,0.000000,None,2,0
32,2020,Manresh Chandra,manresh@gmail.com,zxcvbnm1,My Name is Manresh Chandra. I'm self Motivated...,bc370f5f-7d13-4fe6-9c2c-848198394f8a,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T07:08:47.9644619,2019-12-13T07:08:47.9644619,0.000000,0.000000,None,3,0
33,2019,Test,aakankshi7@gmail.com,zxcvbnm1,test,5a1218d2-5d66-4255-9137-0f7e700bdcab,NaN,Noida,0.0000,0.000000,...,False,False,False,2019-12-05T05:39:51.4928759,2019-12-05T06:41:24.107938,0.000000,0.000000,None,2,0
34,2018,aakankshi6,aakankshi6@gmail.com,zxcvbnm1,A traveller without observation is a bird with...,0ab8257f-7574-476d-b96f-508d3917af9b,NaN,Noida,0.0000,0.000000,...,False,False,False,2019-12-05T05:16:04.4212331,2019-12-05T12:25:13.6221215,0.000000,0.000000,None,0,0
35,2017,aakankshi5,aakankshi5@gmail.com,zxcvbnm1,None,b6fcf970-3271-492b-866c-76238f126c3f,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:06:49.1838089,2019-12-05T05:22:00.9403881,0.000000,0.000000,None,1,0
36,2016,aakankshi4,aakankshi4@gmail.com,zxcvbnm1,None,1b43db89-29a4-4966-ae57-86d705978dd3,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:04:21.8383669,2019-12-05T05:21:57.4139934,0.000000,0.000000,None,0,0
37,2015,aakankshi3,aakankshi3@gmail.com,zxcvbnm1,None,d65f85e3-0f8d-4c67-8de8-1546a7518cba,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:02:05.1655627,2019-12-05T05:21:54.2379269,0.000000,0.000000,None,0,0
38,2014,Aakankshi 2,aakankshi2@gmail.com,zxcvbnm1,ewewrewrew,4e2923a9-b059-4dc9-8d92-ce0cffa84208,NaN,Dada Dev Mandir Road,0.0000,0.000000,...,True,True,False,2019-12-05T05:00:19.5034062,2019-12-05T05:00:19.5034063,77.379025,28.630214,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",5,0
39,2013,Aakankshi 1,aakankshi1@gmail.com,zxcvbnm1,foundations in psychology and sociology and st...,d7fa7194-5ac2-4e32-b11b-3792e5cc067c,NaN,Delhi,0.0000,0.000000,...,True,True,True,2019-12-05T04:38:32.7808454,2019-12-06T05:41:05.3597939,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",269,36
40,2012,Aakankshi Gupta,aakankshi@gmail.com,zxcvbnm1,None,4c02ee6e-2cb5-4b75-888f-4adb7c790dad,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T04:35:42.6189131,2019-12-05T04:35:42.6189131,0.000000,0.000000,None,3,0
41,2011,Aankashi,alokpatel@gmail.com,pankaj@123,its me,4516169a-58e3-4d04-a355-8c608be5d583,NaN,New Delhi,0.0000,0.000000,...,False,False,False,2019-11-30T05:36:52.1332523,2019-12-05T05:21:49.0948144,0.000000,0.000000,None,4,0
42,2010,Test 10,test02@gmail.com,123456,None,ba805b5d-f38f-4a33-9fcb-60f30923479d,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:41:07.8215121,2019-11-27T10:41:07.8215122,0.000000,0.000000,None,3,0
43,2009,Test 9,test10@gmail.com,123456,None,1fa26ffa-465e-499f-ae9d-3e36fb94a0ea,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:20:10.5816545,2019-11-27T10:20:10.5816545,0.000000,0.000000,None,0,0
44,2008,Test 8,test3@test.com,123456,None,822e8f5c-74ba-41f9-911e-9e5a47351dc5,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:09:42.6969868,2019-11-27T10:09:42.6969869,0.000000,0.000000,None,0,0
45,2007,Neeraj Singh,neirajsingh100@gmail.com,100569704678350206382,None,47d25887-1933-4cbc-a4eb-6cc829c9cad6,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-26T12:42:18.6778716,2019-12-05T05:20:40.9827126,0.000000,0.000000,None,2,0
46,2006,Hr. Niels Henriksen,contact@adequateinfosoft.com,354343138574152,i am software developer,347d684e-da9b-450e-bc94-cd5a99b04234,NaN,"Jaypee Greens Pari Chowk, Tugalpur Village, Gr...",0.0000,0.000000,...,False,False,False,2019-11-26T05:58:34.894975,2019-12-05T05:20:37.5393081,77.379024,28.630209,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",11,0
47,2005,Test 6,pankajadequate@gmail.com,sndsjkdsaj161564sasa,None,7a4ae2e1-5b65-4aad-96f0-43336fad5a3b,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-25T13:12:47.6690112,2019-12-05T05:20:34.2935856,0.000000,0.000000,None,2,0
48,2004,Test 5,pankajws@gmail.com,Pankaj@123,None,1fd08288-57aa-41d9-ae44-29fcbb0a78a6,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-25T11:29:06.938541,2019-12-05T05:20:30.604524,0.000000,0.000000,None,4,0
49,2,rajat Saxena,rajat.nirmal@gmail.com,test,abcd,00fb57db-10ad-4661-b3e0-7366c6698ac0,NaN,3465,8.7977,5.834876,...,False,False,False,2019-11-17T16:56:35.8,2019-12-05T05:21:02.1337931,0.000000,0.000000,None,43,0
50,3,Pankaj Patel,Pankaj@gmail.com,123456,None,f6b4bcc8-448b-4b65-84cb-48e9569c5cfe,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T13:25:01.977078,0.000000,0.000000,None,62,0
51,1003,Test 2,pankajabc@gmail.com,Pankaj@123,An ordinary bhartiya..,c8f53478-4cfb-4382-8531-b44b6d20cd8c,NaN,"Jaipur Engineering College Rd, Kukas, Rajastha...",0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-23T13:43:27.5816869,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",16,0
52,1004,Test 2,pankajabcd@gmail.com,Pankaj@123,None,3f92cdef-1d8a-4f08-8468-9938dc9284ce,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:19:23.3650433,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",3,0
53,1005,Test 3,test@test.com,123456,None,cc2ed6c5-0a59-4aca-9b8e-a686e0a4fa03,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:19:29.704463,0.000000,0.000000,None,44,0
54,1006,Test 4,test1@test.com,123456,None,f33f3325-bb08-41a5-b545-d2b5c443720f,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:22:11.8963884,0.000000,0.000000,None,1,0

In [27]:
import pandas as pd

df3 = pd.read_html('https://en.wikipedia.org/wiki/India')
df3

[   Republic of IndiaBhārat Gaṇarājya (see other regional names)  \
 0                                  Flag  State emblem
 1   Motto: "Satyameva Jayate" (Sanskrit)"Truth Alo...
 2   Anthem: "Jana Gana Mana" (Hindi)[a][2][3] "Tho...
 3   National song: .mw-parser-output .nobold{font-...
 4   Territory controlled by India shown in dark gr...
 5                                             Capital
 6                                        Largest city
 7                                  Official languages
 8                       Recognised regional languages
 9                                    Native languages
 10                                    Religion (2011)
 11                                         Demonym(s)
 12                                         Government
 13                                                NaN
 14                                        • President
 15                                   • Vice-President
 16                                   • Prime Minister
 17                                        Legislature
 18                                      • Upper house
 19                                      • Lower house
 20               Independence from the United Kingdom
 21                                                NaN
 22                                         • Dominion
 23                                         • Republic
 24                             • Last polity admitted
 25                                               Area
 26                                            • Total
 27                                        • Water (%)
 28                                         Population
 29                                    • 2023 estimate
 30                                      • 2011 census
 31                                          • Density
 32                                          GDP (PPP)
 33                                            • Total
 34                                       • Per capita
 35                                      GDP (nominal)
 36                                            • Total
 37                                       • Per capita
 38                                        Gini (2019)
 39                                         HDI (2021)
 40                                           Currency
 41                                          Time zone
 42                                                NaN
 43                                        Date format
 44                                       Driving side
 45                                       Calling code
 46                                      ISO 3166 code
 47                                       Internet TLD

    Republic of IndiaBhārat Gaṇarājya (see other regional names).1
 0                                  Flag  State emblem
 1   Motto: "Satyameva Jayate" (Sanskrit)"Truth Alo...
 2   Anthem: "Jana Gana Mana" (Hindi)[a][2][3] "Tho...
 3   National song: .mw-parser-output .nobold{font-...
 4   Territory controlled by India shown in dark gr...
 5   New Delhi .mw-parser-output .geo-default,.mw-p...
 6   .mw-parser-output .plainlist ol,.mw-parser-out...
 7   .mw-parser-output .hlist dl,.mw-parser-output ...
 8   State level and Eighth Schedule[9] 8th Schedul...
 9                                    447 languages[g]
 10  79.8% Hinduism14.2% Islam2.3% Christianity1.7%...
 11                                       Indianothers
 12                     Federal parliamentary republic
 13                                                NaN
 14                                     Droupadi Murmu
 15                                   Jagdeep Dhankhar
 16                                      Narendra Modi
 17                                         Parliament
 18                                        Rajya Sabha
 19                                          Lok Sabha
 20               Independence from the United Kingdom
 21                                                NaN
 22                                     15 August 1947
 23                                    26 January 1950
 24                                        16 May 1975
 25                                               Area
 26        3,287,263[2] km2 (1,269,219 sq mi)[h] (7th)
 27                                                9.6
 28                                         Population
 29                            1,428,627,663[14] (1st)
 30                        1,210,854,977[15][16] (2nd)
 31                   422.0/km2 (1,093.0/sq mi) (30th)
 32                                      2023 estimate
 33                         $13.033 trillion[17] (3rd)
 34                                 $9,073[17] (127th)
 35                                      2023 estimate
 36                          $3.737 trillion[17] (5th)
 37                                 $2,601[17] (139th)
 38                                    35.7[18] medium
 39                           0.633[19] medium · 132nd
 40                             Indian rupee (₹) (INR)
 41                                    UTC+05:30 (IST)
 42                               DST is not observed.
 43                                      dd-mm-yyyy[i]
 44                                           left[20]
 45                                                +91
 46                                                 IN
 47                                       .in (others)              ,
            0                          1
 0     Emblem       Sarnath Lion Capital
 1     Anthem             Jana Gana Mana
 2       Song            "Vande Mataram"
 3   Language        None[248][249][250]
 4   Currency           ₹ (Indian rupee)
 5   Calendar                      Shaka
 6       Bird             Indian peafowl
 7     Flower                      Lotus
 8      Fruit                      Mango
 9     Mammal  Bengal tigerRiver dolphin
 10      Tree                     Banyan
 11     River                     Ganges,
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteIndia topics  \
 0   HistoryOverviews Timeline Years Astronomy Clot...
 1                                             History
 2   Overviews Timeline Years Astronomy Clothing Co...
 3                                           Overviews
 4                                             Ancient
 5                                     Middle Kingdoms
 6                                         Middle Ages
 7                                        Early Modern
 8                                         Late modern
 9                                            Republic
 10                                       Contemporary
 11  GeographyEnvironment Biosphere reserves Climat...
 12                                          Geography
 13  Environment Biosphere reserves Climate Climate...
 14                                        Environment
 15                                          Landforms
 16                                            Regions
 17                                       Subdivisions
 18  PoliticsGovernment Agencies Energy policy Fore...
 19                                           Politics
 20  Government Agencies Energy policy Foreign rela...
 21                                         Government
 22                                                Law
 23  Constitution Penal Code Fundamental rights, pr...
 24                                        Enforcement
 25                                            Federal
 26                                       Intelligence
 27                                           Military
 28                                           Politics
 29  EconomyCompanies BSE SENSEX NIFTY 50 Governmen...
 30                                            Economy
 31  Companies BSE SENSEX NIFTY 50 Government-owned...
 32                                          Companies
 33                                         Governance
 34                                           Currency
 35                                 Financial services
 36                                            History
 37                                             People
 38                                             States
 39                                            Sectors
 40  Society and cultureSociety Caste system Corrup...
 41                                Society and culture
 42  Society Caste system Corruption Demographics I...
 43                                            Society
 44                                            Culture

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteIndia topics.1
 0   HistoryOverviews Timeline Years Astronomy Clot...
 1                                             History
 2   Overviews Timeline Years Astronomy Clothing Co...
 3   Timeline Years Astronomy Clothing Coinage Econ...
 4   Stone Age Indus Valley civilization Vedic peri...
 5                               Middle kingdoms Chola
 6   Medieval India Hoysala Pala Kakatiya Delhi Sul...
 7          Mughals Marathas European trade Bengal War
 8   Colonial Princely state East India Company Pla...
 9   Integration Non-Aligned Movement Five-Year Pla...
 10  History of India (1947–present) Economic liber...
 11  GeographyEnvironment Biosphere reserves Climat...
 12                                          Geography
 13  Environment Biosphere reserves Climate Climate...
 14  Biosphere reserves Climate Climate change Eart...
 15  Beaches Desert Extreme points Glaciers Islands...
 16                    East North Northeast South West
 17  Autonomous administrative divisions Borders To...
 18  PoliticsGovernment Agencies Energy policy Fore...
 19                                           Politics
 20  Government Agencies Energy policy Foreign rela...
 21  Agencies Energy policy Foreign relations Parli...
 22  Constitution Penal Code Fundamental rights, pr...
 23  Constitution Penal Code Fundamental rights, pr...
 24  Federal Border Security Force (BSF) Central In...
 25  Border Security Force (BSF) Central Industrial...
 26  Bureau of Police Research and Development (BPR...
 27                                Army Navy Air Force
 28  Censorship Citizenship Elections Nationalism P...
 29  EconomyCompanies BSE SENSEX NIFTY 50 Governmen...
 30                                            Economy
 31  Companies BSE SENSEX NIFTY 50 Government-owned...
 32  BSE SENSEX NIFTY 50 Government-owned companies...
 33  Ministry of Finance Finance ministers Ministry...
 34  Indian rupee History Historical exchange rates...
 35  Banking Banks Insurance Foreign exchange reser...
 36  Economic Development Economic liberalisation L...
 37  Billionaires Businesspeople Demography Income ...
 38  Andhra Pradesh Assam Bihar Goa Gujarat Haryana...
 39  Agriculture Livestock Fishing Automotive Defen...
 40  Society and cultureSociety Caste system Corrup...
 41                                Society and culture
 42  Society Caste system Corruption Demographics I...
 43  Caste system Corruption Demographics Indians W...
 44  Arts and entertainment Architecture Blogging C...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
                                              History  \
 0  Overviews Timeline Years Astronomy Clothing Co...
 1                                          Overviews
 2                                            Ancient
 3                                    Middle Kingdoms
 4                                        Middle Ages
 5                                       Early Modern
 6                                        Late modern
 7                                           Republic
 8                                       Contemporary

                                            History.1
 0  Overviews Timeline Years Astronomy Clothing Co...
 1  Timeline Years Astronomy Clothing Coinage Econ...
 2  Stone Age Indus Valley civilization Vedic peri...
 3                              Middle kingdoms Chola
 4  Medieval India Hoysala Pala Kakatiya Delhi Sul...
 5         Mughals Marathas European trade Bengal War
 6  Colonial Princely state East India Company Pla...
 7  Integration Non-Aligned Movement Five-Year Pla...
 8  History of India (1947–present) Economic liber...  ,
                  0                                                  1
 0        Overviews  Timeline Years Astronomy Clothing Coinage Econ...
 1          Ancient  Stone Age Indus Valley civilization Vedic peri...
 2  Middle Kingdoms                              Middle kingdoms Chola
 3      Middle Ages  Medieval India Hoysala Pala Kakatiya Delhi Sul...
 4     Early Modern         Mughals Marathas European trade Bengal War
 5      Late modern  Colonial Princely state East India Company Pla...
 6         Republic  Integration Non-Aligned Movement Five-Year Pla...
 7     Contemporary  History of India (1947–present) Economic liber...,
                                            Geography  \
 0  Environment Biosphere reserves Climate Climate...
 1                                        Environment
 2                                          Landforms
 3                                            Regions
 4                                       Subdivisions

                                          Geography.1
 0  Environment Biosphere reserves Climate Climate...
 1  Biosphere reserves Climate Climate change Eart...
 2  Beaches Desert Extreme points Glaciers Islands...
 3                    East North Northeast South West
 4  Autonomous administrative divisions Borders To...  ,
               0                                                  1
 0   Environment  Biosphere reserves Climate Climate change Eart...
 1     Landforms  Beaches Desert Extreme points Glaciers Islands...
 2       Regions                    East North Northeast South West
 3  Subdivisions  Autonomous administrative divisions Borders To...,
                                             Politics  \
 0  Government Agencies Energy policy Foreign rela...
 1                                         Government
 2                                                Law
 3  Constitution Penal Code Fundamental rights, pr...
 4                                        Enforcement
 5                                            Federal
 6                                       Intelligence
 7                                           Military
 8                                           Politics

                                           Politics.1
 0  Government Agencies Energy policy Foreign rela...
 1  Agencies Energy policy Foreign relations Parli...
 2  Constitution Penal Code Fundamental rights, pr...
 3  Constitution Penal Code Fundamental rights, pr...
 4  Federal Border Security Force (BSF) Central In...
 5  Border Security Force (BSF) Central Industrial...
 6  Bureau of Police Research and Development (BPR...
 7                                Army Navy Air Force
 8  Censorship Citizenship Elections Nationalism P...  ,
                                                    0  \
 0                                         Government
 1                                                Law
 2  Constitution Penal Code Fundamental rights, pr...
 3                                        Enforcement
 4                                            Federal
 5                                       Intelligence
 6                                           Military
 7                                           Politics

                                                    1
 0  Agencies Energy policy Foreign relations Parli...
 1  Constitution Penal Code Fundamental rights, pr...
 2  Constitution Penal Code Fundamental rights, pr...
 3  Federal Border Security Force (BSF) Central In...
 4  Border Security Force (BSF) Central Industrial...
 5  Bureau of Police Research and Development (BPR...
 6                                Army Navy Air Force
 7  Censorship Citizenship Elections Nationalism P...  ,
                                                    0  \
 0  Constitution Penal Code Fundamental rights, pr...
 1                                        Enforcement
 2                                            Federal
 3                                       Intelligence

                                                    1
 0  Constitution Penal Code Fundamental rights, pr...
 1  Federal Border Security Force (BSF) Central In...
 2  Border Security Force (BSF) Central Industrial...
 3  Bureau of Police Research and Development (BPR...  ,
               0                                                  1
 0       Federal  Border Security Force (BSF) Central Industrial...
 1  Intelligence  Bureau of Police Research and Development (BPR...,
                                              Economy  \
 0  Companies BSE SENSEX NIFTY 50 Government-owned...
 1                                          Companies
 2                                         Governance
 3                                           Currency
 4                                 Financial services
 5                                            History
 6                                             People
 7                                             States
 8                                            Sectors

                                            Economy.1
 0  Companies BSE SENSEX NIFTY 50 Government-owned...
 1  BSE SENSEX NIFTY 50 Government-owned companies...
 2  Ministry of Finance Finance ministers Ministry...
 3  Indian rupee History Historical exchange rates...
 4  Banking Banks Insurance Foreign exchange reser...
 5  Economic Development Economic liberalisation L...
 6  Billionaires Businesspeople Demography Income ...
 7  Andhra Pradesh Assam Bihar Goa Gujarat Haryana...
 8  Agriculture Livestock Fishing Automotive Defen...  ,

In [9]:
import pandas
df4 = pandas.read_html('https://wifigooglegyan.blogspot.com/')
df4

AttributeError: 'list' object has no attribute 'to_csv'

In [8]:
df5 = pandas.read_excel('CM4.xlsx')
df5

,ID,Start time,Completion time,Email,Name,Total points,Quiz feedback,Last modified time,Name2,Points - Name,...,Points - What will happen on execution of this command : > python manage.py createsuperuser,What does {% include %} does?,Feedback - What does {% include %} does?,Points - What does {% include %} does?,"What is the purpose of the ""forms.py"" file in Django?","Feedback - What is the purpose of the ""forms.py"" file in Django?","Points - What is the purpose of the ""forms.py"" file in Django?","What is the purpose of the ""migrations"" folder in Django?","Feedback - What is the purpose of the ""migrations"" folder in Django?","Points - What is the purpose of the ""migrations"" folder in Django?"
0,1,2023-08-04 14:40:49,2023-08-04 14:43:12,anonymous,NaN,8,NaN,NaN,;lkjhbgvc,NaN,...,0,None of the above,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
1,2,2023-08-04 14:40:29,2023-08-04 14:44:16,anonymous,NaN,8,NaN,NaN,Akash Gupta,NaN,...,1,It will include another template.,NaN,1,To store the project's models,NaN,0,To store the project's static files,NaN,0
2,3,2023-08-04 14:40:59,2023-08-04 14:45:50,anonymous,NaN,3,NaN,NaN,bjnbhjnk,NaN,...,0,It will include another template.,NaN,1,To store the project's views,NaN,0,To store the project's views,NaN,0
3,4,2023-08-04 14:46:12,2023-08-04 14:50:46,anonymous,NaN,7,NaN,NaN,Smriti Ranjan,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's views,NaN,0
4,5,2023-08-04 14:38:33,2023-08-04 14:51:55,anonymous,NaN,19,NaN,NaN,Tannu kumari,NaN,...,0,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
5,6,2023-08-04 14:38:36,2023-08-04 14:52:50,anonymous,NaN,13,NaN,NaN,Seema,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's views,NaN,0
6,7,2023-08-04 14:38:20,2023-08-04 14:53:05,anonymous,NaN,15,NaN,NaN,Mukesh Nirmal,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's static files,NaN,0
7,8,2023-08-04 14:53:09,2023-08-04 14:53:38,anonymous,NaN,0,NaN,NaN,rohit,NaN,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0
8,9,2023-08-04 14:47:39,2023-08-04 14:53:47,anonymous,NaN,8,NaN,NaN,Ramakant,NaN,...,1,It will include content from another template...,NaN,0,To store the project's models,NaN,0,To store the project's database migrations,NaN,1
9,10,2023-08-04 14:46:49,2023-08-04 14:53:48,anonymous,NaN,7,NaN,NaN,Vinod Kumar Sharma,NaN,...,1,It will include content from another template...,NaN,0,To store the project's models,NaN,0,To store the project's database migrations,NaN,1
10,11,2023-08-04 14:39:08,2023-08-04 14:54:12,anonymous,NaN,14,NaN,NaN,Gulshan Kumar Ray,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
11,12,2023-08-04 14:43:52,2023-08-04 14:54:27,anonymous,NaN,18,NaN,NaN,Ashutosh Kumar raj,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
12,13,2023-08-04 14:43:32,2023-08-04 14:54:30,anonymous,NaN,20,NaN,NaN,Amit kumar,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
13,14,2023-08-04 14:42:22,2023-08-04 14:54:36,anonymous,NaN,12,NaN,NaN,Astha sachan,NaN,...,1,It is the same as {% extend %}.,NaN,0,To store the project's forms,NaN,1,To store the project's static files,NaN,0
14,15,2023-08-04 14:39:43,2023-08-04 14:54:41,anonymous,NaN,12,NaN,NaN,Shail Kumari,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
15,16,2023-08-04 14:40:29,2023-08-04 14:54:51,anonymous,NaN,12,NaN,NaN,Vaishnavi Kesherwani,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's models,NaN,0
16,17,2023-08-04 14:42:18,2023-08-04 14:57:24,anonymous,NaN,0,NaN,NaN,Rahul Rai,NaN,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0
17,18,2023-08-04 14:42:58,2023-08-04 14:57:40,anonymous,NaN,8,NaN,NaN,Trapti,NaN,...,1,It will include content from another template...,NaN,0,To store the project's URL configurations,NaN,0,To store the project's database migrations,NaN,1
18,19,2023-08-04 14:42:39,2023-08-04 14:57:44,anonymous,NaN,10,NaN,NaN,Annapurna Rawat,NaN,...,0,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
19,20,2023-08-04 14:45:08,2023-08-04 14:57:53,anonymous,NaN,13,NaN,NaN,Shrey kumar verma,NaN,...,1,It will include content from another template...,NaN,0,To store the project's views,NaN,0,To store the project's database migrations,NaN,1
20,21,2023-08-04 14:50:20,2023-08-04 14:57:55,anonymous,NaN,16,NaN,NaN,Manorama,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
21,22,2023-08-04 14:44:01,2023-08-04 14:57:57,anonymous,NaN,7,NaN,NaN,Ranjeet Kumar tiwari,NaN,...,1,It is the same as {% extend %}.,NaN,0,To store the project's forms,NaN,1,To store the project's models,NaN,0
22,23,2023-08-04 14:43:07,2023-08-04 14:58:13,anonymous,NaN,5,NaN,NaN,Ranjit kumar,NaN,...,1,It is the same as {% extend %}.,NaN,0,NaN,NaN,0,NaN,NaN,0
23,24,2023-08-04 14:46:34,2023-08-04 14:58:33,anonymous,NaN,13,NaN,NaN,Nikhil pandey,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
24,25,2023-08-04 14:44:59,2023-08-04 14:58:35,anonymous,NaN,10,NaN,NaN,Pushpanjali chaurasiya,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's models,NaN,0
25,26,2023-08-04 14:45:52,2023-08-04 14:58:45,anonymous,NaN,11,NaN,NaN,kunjesh yadav,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
26,27,2023-08-04 14:45:21,2023-08-04 15:00:18,anonymous,NaN,18,NaN,NaN,sonali,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
27,28,2023-08-04 14:43:18,2023-08-04 15:00:19,anonymous,NaN,12,NaN,NaN,Pravesh Kumar,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
28,29,2023-08-04 14:45:18,2023-08-04 15:00:28,anonymous,NaN,0,NaN,NaN,NaN,NaN,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0
29,30,2023-08-04 14:58:56,2023-08-04 15:01:05,anonymous,NaN,18,NaN,NaN,Manisha,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's views,NaN,0
30,31,2023-08-04 14:46:10,2023-08-04 15:01:12,anonymous,NaN,8,NaN,NaN,Raja kumar,NaN,...,0,It will include another template.,NaN,1,To store the project's URL configurations,NaN,0,To store the project's database migrations,NaN,1
31,32,2023-08-04 14:46:30,2023-08-04 15:01:29,anonymous,NaN,18,NaN,NaN,Schin singh,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
32,33,2023-08-04 14:59:10,2023-08-04 15:01:55,anonymous,NaN,12,NaN,NaN,Bhagwan Singh,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
33,34,2023-08-04 14:48:15,2023-08-04 15:02:04,anonymous,NaN,11,NaN,NaN,DAMODAR TIWARI,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
34,35,2023-08-04 14:58:08,2023-08-04 15:02:14,anonymous,NaN,11,NaN,NaN,Kavita,NaN,...,1,It is the same as {% extend %}.,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
35,36,2023-08-04 14:58:06,2023-08-04 15:02:17,anonymous,NaN,19,NaN,NaN,Prabhash kumar,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
36,37,2023-08-04 14:58:06,2023-08-04 15:02:44,anonymous,NaN,18,NaN,NaN,Vimal Kumar,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
37,38,2023-08-04 14:57:56,2023-08-04 15:02:58,anonymous,NaN,20,NaN,NaN,Aaditya Sharma,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
38,39,2023-08-04 14:57:26,2023-08-04 15:03:44,anonymous,NaN,11,NaN,NaN,Shiv Shankar Singh,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
39,40,2023-08-04 15:00:07,2023-08-04 15:04:45,anonymous,NaN,18,NaN,NaN,Ranjit Kumar,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
40,41,2023-08-04 14:59:35,2023-08-04 15:06:53,anonymous,NaN,7,NaN,NaN,Sanju Kumar,NaN,...,1,It will include content from another template...,NaN,0,To store the project's URL configurations,NaN,0,To store the project's database migrations,NaN,1
41,42,2023-08-04 14:58:35,2023-08-04 15:07:06,anonymous,NaN,13,NaN,NaN,Aparajita Singh,NaN,...,1,It will include content from another template...,NaN,0,To store the project's URL configurations,NaN,0,To store the project's database migrations,NaN,1
42,43,2023-08-04 14:58:24,2023-08-04 15:07:55,anonymous,NaN,13,NaN,NaN,Rahul Rai,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
43,44,2023-08-04 15:07:26,2023-08-04 15:09:27,anonymous,NaN,18,NaN,NaN,Shivam bharati,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's models,NaN,0
44,45,2023-08-04 15:06:56,2023-08-04 15:09:46,anonymous,NaN,17,NaN,NaN,Anuj pratap singh,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
45,46,2023-08-04 15:08:44,2023-08-04 15:10:38,anonymous,NaN,15,NaN,NaN,Shivam shukla,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
46,47,2023-08-04 14:57:21,2023-08-04 15:12:27,anonymous,NaN,3,NaN,NaN,NaN,NaN,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0
47,48,2023-08-04 15:06:52,2023-08-04 15:12:33,anonymous,NaN,13,NaN,NaN,SANJAY SONKARIYA,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
48,49,2023-08-04 15:09:17,2023-08-04 15:12:34,anonymous,NaN,13,NaN,NaN,Aman Kumar,NaN,...,1,It will include another template.,NaN,1,To store the project's models,NaN,0,To store the project's static files,NaN,0
49,50,2023-08-04 15:00:04,2023-08-04 15:13:26,anonymous,NaN,15,NaN,NaN,sughandha,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
50,51,2023-08-04 15:10:11,2023-08-04 15:14:22,anonymous,NaN,14,NaN,NaN,ANKIT KUMAR GAUTAM,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's models,NaN,0
51,52,2023-08-04 15:13:33,2023-08-04 15:16:50,anonymous,NaN,18,NaN,NaN,Astha sachan,NaN,...,1,It is the same as {% extend %}.,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
52,53,2023-08-04 15:15:59,2023-08-04 15:20:35,anonymous,NaN,17,NaN,NaN,Shail Kumari,NaN,...,1,It is the same as {% extend %}.,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
53,54,2023-08-04 15:11:15,2023-08-04 15:26:17,anonymous,NaN,11,NaN,NaN,NaN,NaN,...,1,It will include another template.,NaN,1,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
54,55,2023-08-04 15:25:40,2023-08-04 15:28:42,anonymous,NaN,17,NaN,NaN,Saksham Katiyar,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
55,56,2023-08-04 15:25:45,2023-08-04 15:28:59,anonymous,NaN,13,NaN,NaN,Sakshi Chaurasia,NaN,...,1,It will include content from another template...,NaN,0,To store the project's models,NaN,0,To store the project's models,NaN,0
56,57,2023-08-04 15:25:58,2023-08-04 15:28:59,anonymous,NaN,10,NaN,NaN,HANUMAN,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1
57,58,2023-08-04 15:26:00,2023-08-04 15:29:11,anonymous,NaN,15,NaN,NaN,Anjali kesherwani,NaN,...,1,It will include content from another template...,NaN,0,To store the project's forms,NaN,1,To store the project's database migrations,NaN,1

In [12]:
import pandas
df4 = pandas.read_html('https://wifigooglegyan.blogspot.com/')
type(df4)

list

In [16]:
a = pandas.DataFrame(df4)
a

C:\Users\s_nas\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\construction.py:553: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])

                                                   0
0                                     0          ...
1                                                ...
2                              0   1
0  बुरे बर्त...

In [17]:
a.to_excel('vinod.xlsx')